openapi: 3.0.3
info:
  title: eduro-hcs
  description: | # language=markdown
    lhwdev가 만든 eduro-hcs(https://hcs.eduro.go.kr)의 비공식 openapi 스펙입니다.  
    이 api의 url은 `https://hcs.eduro.go.kr`입니다.
  contact:
    email: lhwdev6@outlook.com
  
  version: 1.7.59 # aligned with UI version of hcs: https://hcs.eduro.go.kr/#/main/v2/searchSchool:
servers:
  - url: https://hcs.eduro.go.kr
components:
  schemas:
    InstituteInfo:
      type: object
      properties:
        kraOrgNm:
          title: 기관 이름
          type: string
          example:
            - 동대문학교
            - 보성공업고등기술학교
        orgCode:
          title: 기관 코드
          description: | # language=markdown
            알파벳 1글자 + 숫자 10글자로 이루어진 기관 코드입니다. 특히 처음 세 자리는 교육청 코드입니다.
            전체 기관 목록은 [여기](https://docs.google.com/spreadsheets/d/ta6W1a9bLxNySwbuRvQA4fA/edit)에서 확인할 수 있습니다.
          example:
            - B100006026
            - D100000314
        addres:
          title: 주소
          type: string
          example: 부산광역시 동구 초량3동 11671
        atptOfcdcConctUrl:
          title: 시도 교육청 url
paths:
  /v2/searchSchool:
    get:
      summary: 이름으로 기관 검색
      description: |
        학교, 대학교, 교육행정기관이나 학원을 검색할 수 있습니다.
        
        - **학교**: loginType=`school`, orgName, (lctnScCode, schulCrseScCode: 써도, 안써도 됨)
        - **대학**: loginType=`univ`, orgName
        - **교육행정기관**: loginType=`office`, orgName
        - **학원**: loginType=`office`, isAcademySearch=`true`, lctnScCode, sigCode(/v2/getMinors 참고), orgName
      parameters:
        - in: query
          name: loginType
          description: 기관 유형
          schema:
            type: string
            enum: [ school, univ, office ]
          required: true
        - in: query
          name: orgName
          description: 기관 이름
          schema:
            type: string
          required: true
        - in: query
          name: lctnScCode
          description: 지역 코드(loginType이 school이거나 office이고 학원을 검색할 때)
          schema:
            type: string
            oneOf:
              - enum: [ 01 ]
                title: 서울
              - enum: [ 02 ]
                title: 부산
              - enum: [ 03 ]
                title: 대구
              - enum: [ 04 ]
                title: 인천
              - enum: [ 05 ]
                title: 광주
              - enum: [ 06 ]
                title: 대전
              - enum: [ 07 ]
                title: 울산
              - enum: [ 08 ]
                title: 세종
              - enum: [ 10 ]
                title: 경기
              - enum: [ 11 ]
                title: 강원
              - enum: [ 12 ]
                title: 충북
              - enum: [ 13 ]
                title: 충남
              - enum: [ 14 ]
                title: 전북
              - enum: [ 15 ]
                title: 전남
              - enum: [ 16 ]
                title: 경북
              - enum: [ 17 ]
                title: 경남
              - enum: [ 18 ]
                title: 제주
        - in: query
          name: schulCrseScCode
          description: 학교 단계 코드(loginType이 school일 때)
          schema:
            type: string
            oneOf:
              - enum: [ 1 ]
                title: 유치원
              - enum: [ 2 ]
                title: 초등학교
              - enum: [ 3 ]
                title: 중학교
              - enum: [ 4 ]
                title: 고등학교
              - enum: [ 5 ]
                title: 특수학교
        - in: query
          name: isAcademySearch
          description: 학원을 검색하는지 여부(아니면 입력하지 않음)
          schema:
            type: boolean
            enum: [ true, false ]
          required: false
        - in: query
          name: sigCode
          schema:
            type: string
      responses:
        200:
          description: 학교 목록입니다.
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    schulList:
                      type: array
                      items:
                        $ref: '#/components/schemas/InstituteInfo'

