name: Swagger UI documentation
on:
  - push
jobs:
  SwaggerUi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source
      
      - run: |
          mkdir --parents output
      
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: output/ui
          spec-file: source/eduro-hcs-common.yaml
      
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: output/common
          spec-file: source/eduro-hcs.yaml
      - run: |
          cp --recursive source/public output
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          
          enable_jekyll: true
