name: Swagger UI documentation
on:
  - push
jobs:
  SwaggerUi:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui/ui
          spec-file: eduro-hcs-common.json
      
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui/common
          spec-file: eduro-hcs.json
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
